---
# 1. Chặn tag :latest
apiVersion: constraints.gatekeeper.sh/v1beta1 
kind: K8sDisallowedTags
metadata:
  name: block-latest-tag1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "argoproj.io"]
        kinds: ["Pod", "Deployment", "ReplicaSet", "Rollout"]
    excludedNamespaces: ["external-secrets", "kube-system", "argocd"]
  parameters:
    tags: ["latest"]

---
# 2. Bắt buộc có Limits
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: require-resource-limits
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "argoproj.io"]
        kinds: ["Pod", "Deployment", "ReplicaSet", "Rollout"]
    excludedNamespaces: ["external-secrets", "kube-system", "argocd"]

---
# 3. Chặn runAsUser: 0
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockRootUser
metadata:
  name: block-root-user-execution
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "argoproj.io"]
        kinds: ["Pod", "Deployment", "ReplicaSet", "Rollout"]
    excludedNamespaces: ["external-secrets", "kube-system", "argocd"]

---
# 4. Chặn hostNetwork: true
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockHostNetwork
metadata:
  name: block-host-network
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "argoproj.io"]
        kinds: ["Pod", "Deployment", "ReplicaSet", "Rollout"]
    excludedNamespaces: ["external-secrets", "kube-system", "argocd"]