apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
spec:
  automountServiceAccountToken: false  
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo DB_USER=$DB_USER; sleep 3600"]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials-k8s
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials-k8s
              key: password
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000