apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous  
spec:
  refreshInterval: 1m          # sync lại mỗi 1 p
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-credentials-k8s    # tên K8s Secret sẽ tạo ra
    creationPolicy: Owner       # ESO sở hữu — tự xóa khi ExternalSecret bị xóa
  data:
    - secretKey: username         # key trong K8s Secret
      remoteRef:
        key: my-app1/db-credentials # tên trong AWS
        property: username
    - secretKey: password
      remoteRef:
        key: my-app1/db-credentials
        property: password