apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    owner: tan

spec:
  automountServiceAccountToken: false

  containers:
    - name: app
      image: busybox

      command:
        - sh
        - -c
        - |
          while true; do
            echo "DB_USER=$(cat /etc/secrets/username)"
            sleep 300
          done

      volumeMounts:
        - name: db-secret
          mountPath: /etc/secrets
          readOnly: true

      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"

      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000

  volumes:
    - name: db-secret
      secret:
        secretName: db-credentials-k8s