apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials      # K8s Secret vừa tạo
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key